### ISSUE TITLE
wheres the "Win64" folder? can't find it (steam version)

### ISSUE THREAD

**Issue by OBIPPO** [Lyall/JediSurvivorFix#1]
thanks in advance im noob in pcs.

**Comment by Lyall** [comment]
The release zip already has the directory structure that you need, so all you have to do is extract to the game folder. You can get there by finding the game in your steam library and right clicking on it, then click on Manage->Browse local files. 

![image](https://user-images.githubusercontent.com/695941/236638091-d35b335d-51cd-42fa-b7b1-e6fd42cd67eb.png)

This will open the game folder, you can then extract the release zip in to that folder.

**Comment by OBIPPO** [comment]
thanks!!

did it and it seems the black bars are gone, but changing the fov/camera distance does nothing. just changed "false" to "true" and set it to 4 and 8 respectively to test it but it doesn't seem to have changed. anything else to do to adjust fov?

thanks again and excuse my ignorance

**Comment by Lyall** [comment]
Looks like I made a typo on the config check. I will upload a hotfixed version of v1.0.1. 

If you install that version, making sure you overwrite `JediSurvivorFix.ini` in particular then give that a try. If it still doesn't work, please post your `JediSurvivorFix.log` file.

**Comment by OBIPPO** [comment]
I downloaded it and put everything there. I assume to change the fov and camera distance i have to edit these lines? 

Enabled = true
FOVMultiplier = 4
CameraDistance = 3

or leave it on "false"? right now not noticing any difference. probably im doing something wrong

also can't find the log. excuse me for being so dumb :P

**Comment by Lyall** [comment]
Yeah that's how it's meant to be edited. Odd that it's not working but maybe the log will have the answer.

You can find the log right next to the main executable in `SwGame/Binaries/Win64/`.
![image](https://github.com/Lyall/JediSurvivorFix/assets/695941/9d078772-32b0-4d5c-9e1b-b2e0c8a59969)

**Comment by OBIPPO** [comment]
weird, can't find it  there :/

heres a screen of my folder with the modified jedisurvivorfix.ini

https://i.imgur.com/qhvZI9s.png

**Comment by Lyall** [comment]
Ah I see what's gone wrong here. You've downloaded the source code. You want the release zip and extract that to the game folder.

Go to [this page](https://github.com/Lyall/JediSurvivorFix/releases) and download the latest zip.

![image](https://github.com/Lyall/JediSurvivorFix/assets/695941/b040edf1-6041-4e97-9f1e-821722c1993c)

**Comment by OBIPPO** [comment]
im dumb, working fine now thanks!!!
